title: Your awesome title
lang: en
description: Write an awesome description for your new site here

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

edit: true

copyright:
  revision: true

addons:
  - github
  - plugins
  - analytics

addons_branch: true

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
